/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import javax.swing.JOptionPane;

/**
 *
 * @author Victus
 */
public class FrameMencariGame extends javax.swing.JFrame {

    /**
     * Creates new form FrameMencariGame
     */
    public FrameMencariGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        umur = new javax.swing.JTextField();
        Nama_game = new javax.swing.JTextField();
        genre = new javax.swing.JTextField();
        device = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        umur.setBackground(new java.awt.Color(34, 73, 87));
        umur.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        umur.setForeground(new java.awt.Color(255, 255, 255));
        umur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        umur.setBorder(null);
        umur.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurActionPerformed(evt);
            }
        });
        getContentPane().add(umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 150, 10));

        Nama_game.setBackground(new java.awt.Color(34, 73, 87));
        Nama_game.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nama_game.setForeground(new java.awt.Color(255, 255, 255));
        Nama_game.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nama_game.setBorder(null);
        Nama_game.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Nama_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_gameActionPerformed(evt);
            }
        });
        getContentPane().add(Nama_game, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 490, 30));

        genre.setBackground(new java.awt.Color(34, 73, 87));
        genre.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        genre.setForeground(new java.awt.Color(255, 255, 255));
        genre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        genre.setBorder(null);
        genre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });
        getContentPane().add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 150, 10));

        device.setBackground(new java.awt.Color(34, 73, 87));
        device.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        device.setForeground(new java.awt.Color(255, 255, 255));
        device.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        device.setBorder(null);
        device.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        device.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceActionPerformed(evt);
            }
        });
        getContentPane().add(device, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 140, 10));

        harga.setBackground(new java.awt.Color(34, 73, 87));
        harga.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        harga.setBorder(null);
        harga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 140, 10));

        jToggleButton1.setBackground(new java.awt.Color(0,0,0,1));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(225, 225, 225));
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/Menu mencari game.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umurActionPerformed

    private void Nama_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_gameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_gameActionPerformed

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void deviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deviceActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Loading");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMencariGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMencariGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMencariGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMencariGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMencariGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nama_game;
    private javax.swing.JTextField device;
    private javax.swing.JTextField genre;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField umur;
    // End of variables declaration//GEN-END:variables
}
